script += "@echo off\n";
script += "\n";
script += "REM Exit codes:\n";
script += "REM   0 = Success\n";
script += "REM   1 = Invalid arguments\n";
script += "REM   2 = Folder does not exist\n";
script += "REM   3 = No .exe files found\n";
script += "REM   4 = One or more outbound rules failed\n";
script += "REM   5 = One or more inbound rules failed\n";
script += "REM   6 = One or more outbound and inbound rules failed\n";
script += "\n";
script += "REM Require exactly one argument\n";
script += "if \"%~1\"==\"\" (\n";
script += "    echo [ERROR] No folder path was specified.\n";
script += "    exit /b 1\n";
script += ")\n";
script += "\n";
script += "if not \"%~2\"==\"\" (\n";
script += "    echo [ERROR] Too many arguments were specified.\n";
script += "    exit /b 1\n";
script += ")\n";
script += "\n";
script += "REM Get the folder path\n";
script += "set \"folderPath=%~1\"\n";
script += "\n";
script += "REM Verify that the folder exists\n";
script += "if not exist \"%folderPath%\\\" (\n";
script += "    echo [ERROR] The specified folder does not exist: %folderPath%\n";
script += "    exit /b 2\n";
script += ")\n";
script += "\n";
script += "REM Extract the base folder name\n";
script += "for %%A in (\"%folderPath%\") do set \"baseFolderName=%%~nA\"\n";
script += "\n";
script += "REM State flags\n";
script += "set \"foundExe=0\"\n";
script += "set \"outboundFailed=0\"\n";
script += "set \"inboundFailed=0\"\n";
script += "\n";
script += "echo [INFO] Blocking all .exe files in folder: %folderPath%\n";
script += "\n";
script += "REM Process every .exe recursively.\n";
script += "REM A failed firewall command does NOT stop the loop.\n";
script += "for /r \"%folderPath%\" %%F in (*.exe) do (\n";
script += "    set \"foundExe=1\"\n";
script += "\n";
script += "    echo [INFO] Adding outbound block rule for: %%F\n";
script += "\n";
script += "    netsh advfirewall firewall add rule ^\n";
script += "        name=\"Block %baseFolderName% %%~nxF (automated) OUT\" ^\n";
script += "        dir=out ^\n";
script += "        program=\"%%F\" ^\n";
script += "        action=block ^\n";
script += "        enable=yes >nul\n";
script += "\n";
script += "    if errorlevel 1 (\n";
script += "        echo [ERROR] Failed to add outbound firewall rule for: %%F\n";
script += "        set \"outboundFailed=1\"\n";
script += "    )\n";
script += "\n";
script += "    echo [INFO] Adding inbound block rule for: %%F\n";
script += "\n";
script += "    netsh advfirewall firewall add rule ^\n";
script += "        name=\"Block %baseFolderName% %%~nxF (automated) IN\" ^\n";
script += "        dir=in ^\n";
script += "        program=\"%%F\" ^\n";
script += "        action=block ^\n";
script += "        enable=yes >nul\n";
script += "\n";
script += "    if errorlevel 1 (\n";
script += "        echo [ERROR] Failed to add inbound firewall rule for: %%F\n";
script += "        set \"inboundFailed=1\"\n";
script += "    )\n";
script += ")\n";
script += "\n";
script += "REM No executables were found\n";
script += "if \"%foundExe%\"==\"0\" (\n";
script += "    echo [ERROR] No .exe files were found in: %folderPath%\n";
script += "    exit /b 3\n";
script += ")\n";
script += "\n";
script += "REM Report aggregate firewall failures only after every file was attempted\n";
script += "if \"%outboundFailed%\"==\"1\" (\n";
script += "    if \"%inboundFailed%\"==\"1\" (\n";
script += "        echo [ERROR] One or more outbound and inbound firewall rules could not be added.\n";
script += "        exit /b 6\n";
script += "    )\n";
script += "\n";
script += "    echo [ERROR] One or more outbound firewall rules could not be added.\n";
script += "    exit /b 4\n";
script += ")\n";
script += "\n";
script += "if \"%inboundFailed%\"==\"1\" (\n";
script += "    echo [ERROR] One or more inbound firewall rules could not be added.\n";
script += "    exit /b 5\n";
script += ")\n";
script += "\n";
script += "echo [INFO] All .exe files in %folderPath% have been blocked successfully.\n";
script += "exit /b 0\n";
script += "\n";